### ISSUE TITLE
Bug and features

### ISSUE THREAD

**Issue by joemerlino** [evilGoldfish/Forcy#2]
Hi! 
Love your tweak but I noticed a little bug: 
- The enabled killswitch doesn't block the "Swap Invoke Method" if it's on. 

I also have a few suggestions for the next release:
- You can use the code from [ForceTouchActivator](https://github.com/EthanArbuckle/ForceTouchActivator) to implement a new invoke method.
- Possibility to slide directly into the menu options without leave the finger from the display.

Thanks!

**Comment by greenywd** [comment]
Hi!

We will sort out that bug soon and as for your suggestions - 
1. We can't use the code from ForceTouchActivator as it is unlicensed and therefore would need the author's permission to use it (which I'm sure will not happen :/). There is a 'fake force touch' gesture already built into 9.0.2 (at least, not relying on it staying for long) which we are taking advantage on.
2. That is implemented in the beta at https://greenydev.github.io/repo/
