### ISSUE TITLE
Forcy sometimes just stops working

### ISSUE THREAD

**Issue by tlolsthoorn** [evilGoldfish/Forcy#6]
For an unknown reason, Forcy sometimes stops working at random, only to start working again after a respring. I do have to say that I have "Swap Invoke Method" on and that I can still rearrange my icons by swiping up. I have no idea what could be causing the issue and I'm not seeing any crashreport either, is this an issue on your or my end?

_I've an iPod 5,1 if that can be of any help._

**Comment by greenywd** [comment]
timonpls

it's on my end, pretty sure i just fixed it magically
